#!/bin/zsh
# Copy build directory to server and run update on server (~/update)
export SERVER="beimgraben.net"
export USER="frederik"

# Build
npm run build || exit 1

ssh $USER@$SERVER "sudo rm -rf ~/build"
scp -r build $USER@$SERVER:~/build
ssh $USER@$SERVER "sudo ~/update"
